# Generated by Django 4.2.5 on 2023-10-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSVImporter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfile',
            name='name',
        ),
        migrations.AddField(
            model_name='csvfile',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='csv_file',
            field=models.FileField(upload_to='files/', verbose_name='File'),
        ),
    ]
